### ISSUE TITLE
unexpected result

### ISSUE THREAD

**Issue by dav-mcg** [iamstarkov/jss-increase-specificity#1]
neat plugin!  I can't get it to work, though...  when I run this code:

```javascript
var jss = require('jss').default;
var increaseSpecificity = require("jss-increase-specificity");
var preset = require('jss-preset-default').default;

jss
  .setup(preset())
  .use(increaseSpecificity());
 
const styles = {
  button: {
    fontSize: 12,
  },
};
  
console.log(jss.createStyleSheet(styles).toString());
```

I get this output:

```json
".button-0-0 {\n font-size: 12px;\n}"
```

but I'd expect the output to be:

```json
":root:root:root .button-0-0 {\n font-size: 12px;\n}"
```

any idea what might be wrong?  thanks!

**Comment by iamstarkov** [comment]
Hi, @Mavtak

Thanks for trying it out.

what are you package.json?

**Comment by dav-mcg** [comment]
the code I put on this web app should demonstrate:

https://runkit.com/58f11b72af30250012d45fe1/58f11b72af30250012d45fe2/branches/master

**Comment by dav-mcg** [comment]
^ it's using `jss 7.0.3`, `jss-increase-specificity 0.1.0`, and `jss-preset-default 2.0.0`

**Comment by iamstarkov** [comment]
@Mavtak pls, try the latest version and say if it works and please report otherwise
